params:
  num_leaves: 501
  max_depth: 8
  min_data_in_leaf: 285
  learning_rate: 0.020560842890284956
  feature_fraction: 0.6632890063887039
  feature_fraction_bynode: 0.8839177663194971
  bagging_fraction: 0.8911885616675433
  bagging_freq: 9
  lambda_l1: 1.740392180463668
  lambda_l2: 11.514396393425534
  min_gain_to_split: 0.0393280054504595
  max_bin: 255
num_boost_round: 1729
